export type CodeSnippet = {
  readonly dwell: number;
  readonly filename: string;
  readonly fontSize?: number;
  readonly highlightLines: readonly number[];
  readonly id: string;
  readonly lineHeight?: number;
  readonly lines: readonly string[];
  readonly width?: number;
};

export const configLines = [
  "// Wrap Cloudflare's Vite plugin",
  "// This lets Sideffect discovers workflows and write bindings.",
  'import { cloudflare } from "@cloudflare/vite-plugin";',
  'import { defineConfig } from "vite";',
  'import { withCloudflareWorkflows } from "sideffect/vite";',
  "",
  "export default defineConfig({",
  "  plugins: [",
  "    ...withCloudflareWorkflows(cloudflare, {",
  '      workflowPaths: ["src/workflows"],',
  "    }),",
  "  ],",
  "});",
] as const;

export const activityLines = [
  "// Steps are reusable typed activities.",
  "// Payload, result, and Worker bindings stay typed.",
  'export const fetchImage = Step.make("fetch image", {',
  "  payload: Schema.Struct({ imageKey: Schema.String }),",
  "  result: Schema.Struct({ imageKey: Schema.String }),",
  "  run: async ({ imageKey }, ctx) => {",
  "    const object = await ctx.env.BUCKET.get(imageKey);",
  '    if (!object) throw new Error("Image not found");',
  "    return { imageKey };",
  "  },",
  "});",
] as const;

export const workflowLines = [
  "// Compose activities as readable workflow code.",
  "// step.do(...) is the Cloudflare Workflow boundary.",
  'import { describeImage, fetchImage, publishImage } from "./steps";',
  "",
  "const workflow = Workflow.make({",
  '  name: "image-processing",',
  "  payload: Schema.Struct({ imageKey: Schema.String }),",
  "});",
  "",
  "export const imageWorkflow = workflow.toLayer(async ({ payload }, step) => {",
  "  const image = await step.do(fetchImage, { imageKey: payload.imageKey });",
  "  const description = await step.do(describeImage, {",
  "    imageKey: image.imageKey,",
  "  });",
  "",
  '  await step.waitForEvent("await approval", {',
  '    type: "approved",',
  '    timeout: "24 hours",',
  "  });",
  "  await step.do(publishImage, { imageKey: image.imageKey });",
  "",
  "  return description;",
  "});",
] as const;

export const workerLines = [
  "// The generated binding is normal Worker env.",
  "// The handler stays focused on request logic.",
  "export default {",
  "  async fetch(_req: Request, env: Env) {",
  "    const instance = await env.IMAGE_PROCESSING.create({",
  "      params: {",
  '        imageKey: "uploaded-photo-123",',
  "      },",
  "    });",
  "",
  "    return Response.json({ id: instance.id });",
  "  },",
  "};",
] as const;

export const generatedLines = [
  "// Created automatically when Vite starts.",
  "// No manual wrangler workflow config needed.",
  '// Source: Workflow.make({ name: "image-processing" })',
  "export class ImageProcessing extends WorkflowEntrypoint<Env, Params> {}",
  "",
  "declare global {",
  "  namespace Cloudflare {",
  "    interface Env {",
  "      IMAGE_PROCESSING: Workflow<Params>;",
  "    }",
  "  }",
  "}",
] as const;

export const CODE_SNIPPETS = [
  {
    dwell: 100,
    filename: "vite.config.ts",
    highlightLines: [1, 2, 5, 9, 10],
    id: "setup",
    lines: configLines,
  },
  {
    dwell: 100,
    filename: "src/workflows/steps.ts",
    highlightLines: [1, 2, 3, 4, 5, 7, 9],
    id: "activity",
    lines: activityLines,
  },
  {
    dwell: 118,
    filename: "src/workflows/image.ts",
    highlightLines: [1, 2, 3, 11, 12, 16, 20],
    id: "workflow",
    lines: workflowLines,
  },
  {
    dwell: 104,
    filename: "src/index.ts",
    highlightLines: [1, 2, 5, 6, 7],
    id: "worker",
    lines: workerLines,
  },
  {
    dwell: 108,
    filename: "generated by the Vite plugin",
    highlightLines: [1, 2, 4, 9],
    id: "generated",
    lines: generatedLines,
  },
] as const satisfies readonly CodeSnippet[];
