import { writeFileSync } from "node:fs";
import { join, relative } from "node:path";

import type { WorkflowConfigEntry } from "../types.ts";
import type { CapturedSideffectWorkflow } from "./workflow-discovery.ts";

/** @internal Existing native Cloudflare workflow binding preserved from config. */
export interface CapturedNativeWorkflow {
  readonly kind: "native";
  readonly config: WorkflowConfigEntry;
}

/** @internal Workflow binding tracked while generating the virtual entry module. */
export type CapturedWorkflow = CapturedSideffectWorkflow | CapturedNativeWorkflow;

/** @internal Fully resolved inputs for generated `virtual:sideffect/entry`. */
export interface ResolvedVirtualEntryConfig {
  /** Resolved import specifier for the user's original Worker entry. */
  readonly workerImport: string;
  /** Workflow bindings to expose from the generated entry module. */
  readonly workflows: Array<CapturedWorkflow>;
}

export function generateVirtualEntryModule(config: ResolvedVirtualEntryConfig): string {
  const sideffectWorkflows = config.workflows.filter(
    (workflow): workflow is CapturedSideffectWorkflow => workflow.kind === "sideffect",
  );

  if (sideffectWorkflows.length === 0) {
    return `import * as __sideffect_worker from ${JSON.stringify(config.workerImport)};

export * from ${JSON.stringify(config.workerImport)};
export default __sideffect_worker.default ?? {};
`;
  }

  const workflowImports = sideffectWorkflows
    .map((workflow, index) => {
      return `import { ${workflow.layer.exportName} as __sideffect_workflow_${index} } from ${JSON.stringify(workflow.layer.modulePath)};`;
    })
    .join("\n");
  const entries = sideffectWorkflows
    .map((workflow, index) => {
      const className = workflow.config.class_name;
      const literal = JSON.stringify(className);
      return `  ${className}: __sideffectWorkflowLayer(__sideffect_workflow_${index}, ${JSON.stringify("default")}, ${literal}, ${JSON.stringify(workflow.layer.modulePath)}),`;
    })
    .join("\n");
  const exports = sideffectWorkflows
    .map(
      (workflow) =>
        `export const ${workflow.config.class_name} = __sideffect_entrypoints.${workflow.config.class_name};`,
    )
    .join("\n");

  return `import { WorkflowEntrypoints } from "sideffect/cloudflare";
import * as __sideffect_worker from ${JSON.stringify(config.workerImport)};
${workflowImports}

export * from ${JSON.stringify(config.workerImport)};
export default __sideffect_worker.default ?? {};

function __sideffectWorkflowLayer(module, exportName, className, modulePath) {
  const layer = exportName === "default" ? module : module[exportName];
  if (!layer || layer._tag !== "WorkflowLayer") {
    throw new TypeError(\`Expected workflow "\${className}" from "\${modulePath}" to be a Sideffect WorkflowLayer. Export a layer with Workflow.make({ name }).toLayer(...).\`);
  }
  return layer;
}

const __sideffect_entrypoints = WorkflowEntrypoints.make({
${entries}
});

${exports}
`;
}

export function writeWorkflowEnvTypes(root: string, workflows: Array<CapturedWorkflow>): void {
  const sideffectWorkflows = workflows.filter(
    (workflow): workflow is CapturedSideffectWorkflow => workflow.kind === "sideffect",
  );
  if (sideffectWorkflows.length === 0) {
    return;
  }

  writeFileSync(
    join(root, "sideffect-env.d.ts"),
    generateWorkflowEnvTypes(root, sideffectWorkflows),
  );
}

function generateWorkflowEnvTypes(
  root: string,
  workflows: Array<CapturedSideffectWorkflow>,
): string {
  const imports = workflows
    .map((workflow, index) => {
      const path = relative(root, workflow.layer.modulePath)
        .replace(/\\/g, "/")
        .replace(/\.[cm]?[jt]sx?$/, "");
      const specifier = path.startsWith(".") ? path : `./${path}`;
      return `import type { ${workflow.layer.exportName} as __SideffectWorkflow${index} } from ${JSON.stringify(specifier)};`;
    })
    .join("\n");
  const envBindings = workflows
    .map((workflow, index) => {
      const payload = `__SideffectWorkflowPayload<typeof __SideffectWorkflow${index}>`;
      return `    ${workflow.config.binding}: __SideffectCloudflareWorkflow<${payload}>;`;
    })
    .join("\n");
  const cloudflareEnvBindings = workflows
    .map((workflow, index) => {
      const payload = `__SideffectWorkflowPayload<typeof __SideffectWorkflow${index}>`;
      return `      ${workflow.config.binding}: __SideffectCloudflareWorkflow<${payload}>;`;
    })
    .join("\n");

  return `// Generated by Sideffect. Do not edit.
import type { WorkflowLayer } from "sideffect";
${imports}

type __SideffectCloudflareWorkflow<Payload> = Workflow<Payload>;
type __SideffectWorkflowPayload<T> = T extends WorkflowLayer<infer Payload, any> ? Payload : never;

declare global {
  interface Env {
${envBindings}
  }

  namespace Cloudflare {
    interface Env {
${cloudflareEnvBindings}
    }
  }
}

export {};
`;
}
